users/forms.py
import re

import pyotp
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, SubmitField, PasswordField, IntegerField, BooleanField
from wtforms.validators import DataRequired, Email, ValidationError, EqualTo, Length

# Password validators
def character_check(form, field):
    # Excludes these chars
    excluded_chars = "*?!'^+%&/()=}][{$#@<>"
    for char in field.data:
        if char in excluded_chars:
            # Shows the user which char isn't allowed
            raise ValidationError(f"Character {char} is not allowed.")


def phone_check(form, field):
    # Only allows ****-***-**** for a phone number format
    p = re.compile('\d{4}-\d{3}-\d{4}')
    if not p.match(field.data):
        # If entered number in wrong show this message
        raise ValidationError("Phone number must be in this format XXXX-XXX-XXXX (including the dashes)")


def password_check(form, field):
    # Regular expression restricting what needs to be in password
    p = re.compile(r'(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d])')
    if not p.match(field.data):
        # If format doesn't match show message
        raise ValidationError(
            "Password must contain 1 digit, 1 lowercase letter, 1 uppercase letter and, 1 special character, and 6-12 characters in length")


def postcode_check(form, field):
    # Restricts the format of the post codes
    x = re.compile('[A-Za-z]\d\s\d[A-Za-z][A-Za-z]')
    y = re.compile('[A-Za-z]\d\d\s\d[A-Za-z][A-Za-z]')
    z = re.compile('[A-Za-z][A-Za-z]\d\s\d[A-Za-z][A-Za-z]')

    if not (x.match(field.data) or y.match(field.data) or z.match(field.data)):
        # If format doesn't match show message
        raise ValidationError(
            "Postcode should be in these formats. (X: LETTERS Y: DIGITS with spaces) *XY YXX* *XYY YXX* *XXY YXX*")


def year_check(form, field):
    # Restricts the format of the date of birth
    x = re.compile('\d{2}/\d{2}/\d{4}')
    if not x.match(field.data):
        # If format doesn't match show message
        raise ValidationError("Error in date of birth should be in this format DD/MM/YYYY")

# Creates the form fields and validators for register form
class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    firstname = StringField('First name', validators=[DataRequired(), character_check])
    lastname = StringField('Last name', validators=[DataRequired(), character_check])
    phone = StringField('Phone number', validators=[DataRequired(), phone_check])
    password = PasswordField('Password', validators=[DataRequired(), password_check, Length(min=6, max=12)])
    confirm_password = PasswordField('Confirm password', validators=[DataRequired(), Length(min=6, max=12), EqualTo('password', message='Passwords must match')])
    date_of_birth = StringField('Date of Birth', validators=[DataRequired(), year_check])
    post_code = StringField('Post Code', validators=[DataRequired(), postcode_check])
    submit = SubmitField()

# Creates the form fields and validators for login form
class LoginForm(FlaskForm):

    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    pin = StringField('Pin', validators=[DataRequired(), Length(min=6, max=6, message="Pin must be 6 digits")])
    postcode = StringField('Post Code', validators=[DataRequired(), postcode_check])
    recaptcha = RecaptchaField()
    submit = SubmitField()

# Creates the form fields and validators for password form
class PasswordForm(FlaskForm):
    current_password = PasswordField(id='password', validators=[DataRequired()])
    show_password = BooleanField('Show password', id='check')
    new_password = PasswordField(validators=[DataRequired(), Length(min=6, max=12), password_check])
    confirm_new_password = PasswordField(validators=[DataRequired(), EqualTo('new_password', message='Passwords must match')])
    submit = SubmitField('Change Password')

users/views.py
# IMPORTS
import logging
import bcrypt
import pyotp
from flask import Blueprint, render_template, flash, redirect, url_for, session, request
from flask_login import login_user, current_user, logout_user, login_required
from markupsafe import Markup
from datetime import datetime
from app import db, requires_roles
from models import User
from users.forms import RegisterForm, LoginForm, PasswordForm

# CONFIG
users_blueprint = Blueprint('users', __name__, template_folder='templates')



@users_blueprint.route('/admin_register', methods=['GET', 'POST'])
@login_required
@requires_roles('admin')
def admin_register():
    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('users/register.html', form=form)

        # create a new user with the form data
        new_admin = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        postcode=form.post_code.data,
                        dateofbirth=form.date_of_birth.data,
                        pin_key=pyotp.random_base32(),
                        role='admin')

        # add the new user to the database
        db.session.add(new_admin)
        db.session.commit()

        #Flashing a message to let the admin know a new admin has been added
        flash(Markup('New admin has been added to the system, authorisation set up manually'))
        # Logs when a user registered
        logging.warning('SECURITY - Admin Registered [%s, %s]', form.email.data, request.remote_addr)
        return redirect(url_for('admin.admin'))
        # Redirects so user can set up 2FA
    # if request method is GET or form not valid re-render signup page
    return render_template('users/register.html', form=form)


# VIEWS
# view registration

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # Prevents users already registered and logged in from accessing
    if current_user.is_authenticated:
        if current_user.role == 'admin':
            flash("This account is already registered")
            return redirect(url_for('admin.admin'))
        elif current_user.role == 'user':
            flash("This account is already registered")
            return redirect(url_for('lottery.lottery'))

    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('users/register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        postcode=form.post_code.data,
                        dateofbirth=form.date_of_birth.data,
                        pin_key=pyotp.random_base32(),
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()
        # Logs when a user registered
        logging.warning('SECURITY - User Registered [%s, %s]', form.email.data, request.remote_addr)
        session['email'] = new_user.email
        # Redirects so user can set up 2FA
        return redirect(url_for('users.setup_2fa'))
    # if request method is GET or form not valid re-render signup page
    return render_template('users/register.html', form=form)


# view user login
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    # Prevents users already logged in from accessing
    # Prevents users already registered and logged in from accessing
    if current_user.is_authenticated:
        if current_user.role == 'admin':
            flash("This account is already logged in")
            return redirect(url_for('admin.admin'))
        elif current_user.role == 'user':
            flash("This account is already logged in")
            return redirect(url_for('lottery.lottery'))
    form = LoginForm()

    if not session.get('authentication_attempts'):
        session['authentication_attempts'] = 0

        #user.verify_pin(form.pin.data) or not

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # Checks password and pin matches what's in the database
        if not user or not user.verify_password(form.password.data) or not user.verify_postcode(form.postcode.data):
            # If incorrect data entered will add 1 to authentication attempts
            session['authentication_attempts'] += 1
            # Adds invalid login attempts to the log file
            logging.warning('SECURITY - Invalid login attempt [%s, %s]', form.email.data, request.remote_addr)
            # Sets max authentication attempts to 3
            if session.get('authentication_attempts') >= 3:
                # If user has more than 3 failed login attempts flash message with link to reset login attempts
                flash(Markup(
                    'Number of incorrect login attempts exceeded. Please click <a href="/reset">here</a> to reset.'))
                # Redirects to login page
                return render_template('users/login.html')
            # Flashes message with remaining login attempts
            flash('Please check your login details and try again, {} login attempts remaining'.format(
                3 - session.get('authentication_attempts')))
            return render_template('users/login.html', form=form)
        else:
            login_user(user)
            # Updates the users last and current log in
            current_user.last_login = current_user.current_login
            current_user.current_login = datetime.now()
            # Updates the users last and current ip used to log in
            current_user.last_ip_login = current_user.current_ip_login
            current_user.current_ip_login = request.remote_addr
            # Updates the total number of successful logins for the current user
            current_user.successful_logins += 1
            db.session.commit()
            # Logs when a user logged in
            logging.warning('SECURITY - User Login [%s, %s, %s]', current_user.id, current_user.email,
                            request.remote_addr)
            # If a normal user redirect to ltotery page
            if current_user.role == 'user':
                return redirect(url_for('lottery.lottery'))
            # If admin redirect to admin page
            elif current_user.role == 'admin':
                return redirect(url_for('admin.admin'))

    return render_template('users/login.html', form=form)


# Sets up 2FA for the user
@users_blueprint.route('/setup_2fa')
def setup_2fa():
    if 'email' not in session:
        return redirect(url_for('users.register'))
    user = User.query.filter_by(email=session['email']).first()
    if not user:
        return redirect(url_for('users.register'))
    del session['email']
    return render_template('users/setup_2fa.html', email=user.email, uri=user.get_2fa_uri()), 200, {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
    }


# view user profile
@users_blueprint.route('/profile')
def profile():
    return render_template('users/profile.html', name="PLACEHOLDER FOR FIRSTNAME")


# view user account
@users_blueprint.route('/account')
@login_required
def account():
    return render_template('users/account.html',
                           acc_no=current_user.id,
                           email=current_user.email,
                           firstname=current_user.firstname,
                           lastname=current_user.lastname,
                           phone=current_user.phone)


# Logs out a user
@users_blueprint.route('/logout')
@login_required
def logout():
    # Logs when a user logs out
    logging.warning('SECURITY - User log out [%s, %s, %s]', current_user.id, current_user.email, request.remote_addr)

    logout_user()
    return render_template('main/index.html')


# Resets user login attempts
@users_blueprint.route('/reset')
def reset():
    session['authentication_attempts'] = 0
    return redirect(url_for('users.login'))


# Used to update the users password
@users_blueprint.route('/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if not current_user.verify_password(form.current_password.data):
            flash("Current password is incorrect")
        elif current_user.verify_password(form.new_password.data):
            flash("New password cant be the same as the old password")
        else:
            # Hashes the updated password and updates it to current
            current_user.password = bcrypt.hashpw(form.new_password.data.encode('utf-8'), bcrypt.gensalt())
            # Commits change to database
            db.session.commit()
            flash("Password changed successfully")
            return redirect(url_for('users.account'))

    return render_template('users/update_password.html', form=form)

templates/users/account.html
{% extends "base.html" %}

{% block content %}

<div class="column is-6 is-offset-3">
    <h3 class="title">Your Account</h3>

    <div class="box">
        {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
        <table class="table">
        <tbody>
            <tr>
                <th>Account No.</th>
                <th>{{ acc_no }}</th>
            </tr>
            <tr>
                <th>Email</th>
                <th>{{ email }}</th>
            </tr>
            <tr>
                <th>First Name</th>
                <th>{{ firstname }}</th>
            </tr>
            <tr>
                <th>Last Name</th>
                <th>{{ lastname }}</th>
            </tr>
            <tr>
                <th>Phone No.</th>
                <th>{{ phone }}</th>
            </tr>
            <tr>
                <th>Date of birth</th>
                <th>{{ current_user.dateofbirth }}</th>
            </tr>
            <tr>
                <th>Post Code</th>
                <th>{{ current_user.postcode }}</th>
            </tr>
            <tr>
                <th>Role</th>
                <th>{{ current_user.role }}</th>
            </tr>
            <tr>
                <th>Password</th>
                <td><a style='color: blue' href="{{ url_for('users.update_password') }}">Change Password</a></td>
            </tr>
        </tbody>
        </table>
    </div>
</div>


{% endblock %}

templates/users/login.html
{% extends "base.html" %}

{% block content %}

 <div class="column is-5 is-offset-4">
    <h3 class="title is-3">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}.
                </div>
            {% endif %}
        {% endwith %}
    {% if form %}
    <form method="POST">
    <div class="field">
    {{ form.csrf_token() }}
    <div class="control">
        {{ form.email(class="input", placeholder="Email") }}
        {% for error in form.email.errors %}
        {{ error }}
        {% endfor %}
    </div>
    </div>
    <div class="field">
    {{ form.csrf_token() }}
    <div class="control">
        {{ form.password(class="input", placeholder="Password") }}
        {% for error in form.password.errors %}
        {{ error }}
        {% endfor %}
    </div>
    </div>
    <div class="field">
    {{ form.csrf_token() }}
        <div class="control">
        {{ form.postcode(class="input", placeholder="Postcode") }}
        {% for error in form.postcode.errors %}
        {{ error }}
        {% endfor %}
    </div>
    </div>

    <div class="field">
    {{ form.csrf_token() }}
    <div class="control">
        {{ form.pin(class="input", placeholder="Pin") }}
        {% for error in form.pin.errors %}
        {{ error }}
        {% endfor %}
    </div>
    </div>
    <div>
        {{ form.recaptcha }}
        {% for error in form.recaptcha.errors %}
        {{ error }}
        {% endfor %}
    </div>

    <div>
        {{ form.submit(class="button is-info is-centered") }}

    </div>
    </form>
    {% endif %}
    </div>
 </div>

{% endblock %}

templates/users/register.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                        {% for error in form.email.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.firstname(class="input", placeholder="First Name") }}
                        {% for error in form.firstname.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.lastname(class="input", placeholder="Last Name") }}
                        {% for error in form.lastname.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.phone(class="input", placeholder="Phone") }}
                        {% for error in form.phone.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {% for error in form.password.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                        {% for error in form.confirm_password.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.date_of_birth(class="input", placeholder="Date of birth") }}
                        {% for error in form.date_of_birth.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.post_code(class="input", placeholder="Post Code") }}
                        {% for error in form.post_code.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>
                </div>



                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/setup_2fa.html
{% extends "base.html" %}

{% block content %}

    <p>To set up 2 factor authentication under the account name {{ email }},
scan the following QR code with your smartphone's authenticator app:</p>
    <p><img src="{{ qrcode(uri, box_size=5, border=5) }}"></p>
    <p>Once set up, please go to the <a href="{{ url_for('users.login') }}"><u>Login</u></a> page</p>

{% endblock %}

templates/users/update_password.html
{% extends 'base.html' %}

{% block content %}
    <script type="text/javascript" src="{{ url_for('static', filename='listeners.js') }}"></script>
    <div class="column is-5 is-offset-4">
        <h3 class="title">Change Password</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.current_password(class="input", placeholder="Current Password") }}
                        {% for error in form.current_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.show_password() }}
                        {{ form.show_password.label }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.new_password(class="input", placeholder="New Password") }}
                        {% for error in form.new_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_new_password(class="input", placeholder="Confirm New Password") }}
                        {% for error in form.confirm_new_password.errors %} {{ error }} {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}